config/routes.rb
Rails.application.routes.draw do
  resources :messages
  root to: 'messages#index'
  get '/happyweek', to: 'happy_week#index'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/happy_week_node.rb
class HappyWeekNode < ActiveRecord::Base
  has_ancestry
end

app/models/message.rb
class Message < ActiveRecord::Base
  has_ancestry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/happy_week_controller.rb
class HappyWeekController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
    @message = Message.new(parent_id: params[:parent_id])
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to messages_url
    else
      render :new
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to messages_url
  end

  private

  def message_params
    params.require(:message).permit(:content, :parent_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/happy_week_nodes_helper.rb
module HappyWeekNodesHelper

  def is_happy?(nodes)
    nodes.each do |node, children|
      return done?(node.activity) if children.empty?
      case node.operator
        when 'AND' then return is_happy?(left(children)) && is_happy?(right(children))
        when 'OR' then return is_happy?(left(children)) || is_happy?(right(children))
        else raise 'undefined operator'
      end
    end
  end

  private

  def done?(activity)
    Activity.exists?(name: activity)
  end

  def right(children)
    Hash[*children.to_a.at(1)]
  end

  def left(children)
    Hash[*children.first]
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def nested_messages(messages)
    messages.map do |message, sub_messages|
      render(message) + content_tag(:div, nested_messages(sub_messages), class: 'nested_messages')
    end.join.html_safe
  end
end

app/views/happy_week/index.html.erb
<h1>Happy Week</h1>

<%= display_happy_week_nodes HappyWeekNode.arrange %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AncestryDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message do |f| %>
  <%= f.hidden_field :parent_id %>
  <p>
    <%= f.label :content, "New Message" %><br />
    <%= f.text_area :content, :rows => 8 %>
  </p>
  <p><%= f.submit "Post Message" %></p>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="created_at"><%= message.created_at.strftime("%B %d, %Y") %></div>
  <div class="content">
    <%= link_to message.content, message %>
  </div>
  <div class="actions">
    <%= link_to "Reply", new_message_path(:parent_id => message) %> |
    <%= link_to "Destroy", message, :confirm => "Are you sure?", :method => :delete %>
  </div>
</div>

app/views/messages/index.html.erb
<h1>Messages</h1>

<%= nested_messages Message.arrange(order: :created_at) %>

<%= render "form" %>

app/views/messages/new.html.erb
<h1>Reply</h1>

<%= render @message.parent if @message.parent %>

<%= render "form" %>

<p><%= link_to "Back to Messages", messages_path %></p>

app/views/messages/show.html.erb
<h1>Message</h1>

<%= nested_messages @message.subtree.arrange(order: :created_at) %>

<p><%= link_to "Back to All Messages", messages_path %></p>